### PR TITLE
Updating costs for single axis tracking

### PR DESCRIPTION
**Pull request by KatherineRinaldi**
Created a new case input file (case_input_test_191017.xlsx and .csv) with updated costs for single axis tracking PV and deleted case_input_test_191008.csv but kept the xlsx file so people can compare results if necessary

### CODE REVIEW

**Comment by truggles** [comment]
Thanks for the update.  I like how you renamed the file so we can easily track the changes between the two versions.

I am noticing that we have the same 1.95287E-02 ($/h)/kW value also for `FIXED_COST_SOLAR2` and `FIXED_COST_CSP`

I think it makes sense to also update SOLAR2, not sure on CSP.  @candisehenry can you comment on CSP?  Why was the CSP cost the same in the first place?

**Comment by candisehenry** [comment]
@jacquelinedowling can you please answer this question about CSP? I believe you were the one who updated the values, correct? When I added CSP to MEM, I just used generic values to test the code (I didn't actually obtain correct costs).

**Comment by KatherineRinaldi** [comment]
OK edited SOLAR2 so it's updated now (forgot about that my bad). Will hold off on CSP until we have word from Jackie

**Comment by jacquelinedowling** [comment]
Hi all,
I have some cost values for CSP. Nate and I agreed on costs, but not lifetimes, decay rates, appropriate references, etc. Those are not all triple checked yet, and will take some time to do so. Let's update for single-axis tracking first and then CSP later. My goal is to publish the PGP paper first and then move to CSP/ redox flow batteries.
Best,
Jackie

**Comment by truggles** [comment]
Thanks @jacquelinedowling, let's merge this for now.  I'll make an issue just so people know CSP values are not final.

**Pull request merged**
