### PR TITLE
Temoa work

### PR DESCRIPTION
**Pull request by truggles**
* Add CURTAILMENT_CSP to results
* Deals with cases where batteries and storage are included in one case but not others.  This is dealt with by skipping the plotting of storage results when storage is not included.

@KenCaldeira, is there a much more graceful way to do both of these?

### CODE REVIEW

**Comment by KenCaldeira** [comment]
On a quick look, all seems reasonable.

Right now, I think some curtailment is computed in Core_Model.py and soe in
Save_Basic_Results.py.

Really, the stuff in Core_Model.py should be eliminated, since
Core_Model.py should concern itself with primary inputs and outputs, and
derived outputs should be calculated elsewhere.

**Comment by truggles** [comment]
The newest commit has the change we discussed today, @KenCaldeira.

**Comment by truggles** [comment]
Let me know if anyone is not okay with this merge...

**Review by d-farnham — COMMENTED** [review]
Looks good to me

**Pull request merged**
